version: '3.8'

services:
  db-acj:
    image: mariadb:10.6
    restart: always
    volumes:
      - db-data-ria2022:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: webapi
      MYSQL_DATABASE: webapi
      MYSQL_USER: webapi
      MYSQL_PASSWORD: webapi
    ports:
      - 1005:3306

volumes:
  db-data-ria2022:
    driver: local

